spring.application.name=sbsample
spring.web.resources.chain.strategy.content.enabled=false
# spring.web.resources.chain.strategy.content.paths=/** # This line is no longer needed when content strategy is disabled.
